 # Macro file for the visualization setting for the initialization phase 
# of the B2 example when running in interactive mode
#
# 0:GEN->RECO, 1:GEN->DIGI, 2:GEN->SIM, 3: SIM -> RECO, 4: SIM -> DIFI, 5 : DIGI -> RECO
# Gen 3: corsikadata_4m.root Gen 4: flux_Pethu_FLUKA_SIBYLL_Surya.root
/mical/run/inout 0
/mical/run/isVis 0
/mical/run/isXterm 0
/mical/gun/Gen 4
/mical/gun/TopTrgLay 3
/mical/gun/BottomTrgLay 0
/mical/gun/pid 13
/mical/gun/rndm off
#/mical/gun/vxsmear 0
/mical/gun/vxsmear -100.
#/mical/gun/vysmear 0.
/mical/gun/vysmear -100.
/mical/gun/vzsmear -10.
#/mical/gun/vzsmear 0.
/mical/gun/energy 3.6
/mical/gun/ensmear 0


#/mical/cal0SD/CorrTimeSmr 1
#/mical/cal0SD/UnCorrTimeSmr 1 
#/mical/cal0SD/CorrIneffiCmd 0.1
#/mical/cal0SD/UnCorrXIneffiCmd 0
#/mical/cal0SD/UnCorrYIneffiCmd 0
#/mical/cal0SD/TimeToDigiConv 0.1
#/mical/cal0SD/SigSpeed 0.15
#/mical/cal0SD/CorrNoise1 0
#/mical/cal0SD/CorrNoise2 0
#/mical/cal0SD/CorrNoise3 0
#/mical/cal0SD/RootRandom 0
#/mical/cal0SD/RandomNoise 0

/mical/gun/firstEvt 0
#/mical/gun/corsika_file_dir ./
#/mical/gun/corsika_file corsikadata_4m.root
/mical/gun/flux_file_dir ./
/mical/gun/flux_file flux_Pethu_FLUKA_SIBYLL_Surya.root

/mical/run/firstEvt 1
/mical/run/input_dir ./

/mical/run/collated_input 1
/mical/run/collated_input_file Collated_evtraw_20181120_20210813ai_5of8.root


/mical/run/corr_pos_time_input 1
/mical/run/corr_pos_time_input_file corrections_pos_time_26122018.root




#Left wall (cm)
#/mical/gun/incpos -380 -1173 -20

#/mical/gun/incdir 0.8358 0.265 -0.480




#/mical/gun/thsmear 0
#/mical/gun/phsmear 0

#top layer
#/mical/gun/incpos 2 -1173 -50
/mical/gun/incpos 0 -1073 -50
/mical/gun/incdir 0.30 0.31224989992 -0.95
#/mical/gun/incdir 0 0 -1

/mical/gun/thsmear -427
/mical/gun/phsmear -3142

#right wall

#/mical/gun/incpos 400 -1173 -35
#/mical/gun/incdir -1.16023 0.177071 -0.500493        
#/mical/gun/thsmear 0
#/mical/gun/phsmear 0


#back wall


#/mical/gun/incpos 0 -810 -100
#/mical/gun/incdir 0.0983875 -0.951257 -0.623551
#/mical/gun/thsmear 0
#/mical/gun/phsmear 0


/mical/run/output_file test1_coll
/mical/run/input_file test1_coll






# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
#$/vis/open OGL 600x600-0+0
#$/vis/viewer/set/viewpointVector 0.0 0.0 0.0
#
# Use this open statement to create an OpenInventor view:
#/vis/open OIX
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
#/vis/viewer/set/viewpointThetaPhi 89.9 -90
/vis/viewer/set/viewpointThetaPhi 0 0
#/vis/viewer/set/viewpointVector 0.0 -1375.0 0.0
# Specify zoom value:
#/vis/viewer/zoom 300.0
#
# Specify style (surface, wireframe, auxiliary edges,...)
#/vis/viewer/set/style wireframe
#/vis/viewer/set/auxiliaryEdge true
#/vis/viewer/set/lineSegmentsPerCircle 100
#


# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
#/vis/scene/add/hits 
#/vis/scene/add/date
#/vis/scene/add/eventID
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
 #(if too many tracks cause core dump => /tracking/storeTrajectory 0)
#

/vis/modeling/trajectories/create/drawByAttribute
/vis/modeling/trajectories/drawByAttribute-0/setAttribute CPN
/vis/modeling/trajectories/drawByAttribute-0/addValue brem_key eBrem
/vis/modeling/trajectories/drawByAttribute-0/brem_key/setLineColour green 






# Draw hits at end of event:
/vis/scene/add/hits
#
# To draw only gammas:
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu+
/vis/filtering/trajectories/particleFilter-0/add mu-
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
/vis/modeling/trajectories/list
/vis/modeling/trajectories/drawByParticleID-0/set mu+ red
/vis/modeling/trajectories/drawByParticleID-0/set mu- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
/vis/modeling/trajectories/drawByParticleID-0/set e- yellow
#


# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts false

# For file-based drivers, use this to create an empty detector view:
# Camera and lights commands
#/vis/viewer/set/viewpointVector -0.121795 0.0348995 -0.991942
#/vis/viewer/set/upVector 0 1 0
#$/vis/viewer/set/projection orthogonal
#$/vis/viewer/zoomTo 300.0
#$/vis/viewer/scaleTo 1 1 1
#$/vis/viewer/set/targetPoint 1.73182 0 0 m  
# Note that if you have not set a target point, the vis system sets
# a target point based on the scene - plus any panning and dollying -
# so don't be alarmed by strange coordinates here.
#$/vis/viewer/dollyTo 0 fm 
#$/vis/viewer/set/lightsMove object
#$/vis/viewer/set/lightsVector 1 1 1
#$/vis/viewer/set/rotationStyle constrainUpDirection
/vis/viewer/set/background 1 1 1
#$/vis/viewer/set/defaultColour 1 1 1 1
#$/vis/viewer/set/defaultTextColour 0 0 1 1
#
# Drawing style commands
#$/vis/viewer/set/style wireframe
#$/vis/viewer/set/hiddenEdge false
#$/vis/viewer/set/auxiliaryEdge false
#$/vis/viewer/set/hiddenMarker false
#$/vis/viewer/set/globalLineWidthScale 1
#$/vis/viewer/set/globalMarkerScale 1

# Scene-modifying commands
#$/vis/viewer/set/culling global true
#$/vis/viewer/set/culling invisible true
#$/vis/viewer/set/culling density false
#$/vis/viewer/set/culling coveredDaughters false
#$/vis/viewer/set/sectionPlane off
#$/vis/viewer/set/cutawayMode union
#$/vis/viewer/clearCutawayPlanes
# No cutaway planes defined.
#$/vis/viewer/set/explodeFactor 1 0 0 0 fm 
#$/vis/viewer/set/lineSegmentsPerCircle 24


#
# Touchable commands
# None
#/vis/viewer/flush
/run/beamOn 1000